name: Build & Test

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        working-directory: ./src/
        run: dotnet restore

      - name: Dotnet build
        working-directory: ./src/
        run: dotnet build --configuration Release --no-restore
        
  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      TEST_PROJECT_DIR: ./test/RepoStatusTable.UnitTests
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install Dependencies
        working-directory: ${{ env.TEST_PROJECT_DIR }}
        run: dotnet restore

      - name: Run Tests
        working-directory: ${{ env.TEST_PROJECT_DIR }}
        run: | 
          dotnet test \
            --no-restore \
            --verbosity normal \
            --logger trx \
            --results-directory "TestResults"
          
      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: dotnet-results
          path: TestResults
