name: Create Repo Visualization

on:
  push:
    branches: [ trunk ]
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Create diagram
        uses: githubocto/repo-visualizer@0.7.1
        with:
          output_file: "diagram.svg"
          artifact_name: "RepoVisualization"
          excluded_paths: "ignore,.github" 
          commit_message: "Update repo visualization [actions skip]"